### ISSUE TITLE
Make bot stop sleeping.

### ISSUE THREAD

**Issue by latachz** [latachz/DevscordBot#1]
As we know in the free Heroku plan, the inactive application is getting slept. We have to make any kind of request which will be performed every 28 minutes.

**Comment by Marcin99b** [comment]
We can use mee6 bot on private channel - visible only for bots... or bots and admins

Mee6 bot have option "timer" => send X message on X channel regularly 
Then we will need only something like ping function in DevscordBot

**Comment by latachz** [comment]
We don't have to do it. We only need to send a simple request from bot to server. We don't even have to process that data.
